language: node_js
node_js:
  - lts/*
services:
  - docker

before_install:
  - npm install
  - npx tsc
  - npx node-sass --recursive ./src --output ./src
  - ./cleanRelease.sh
  - docker build -t ghcr.io/nils-witt/s-plan_display:"$DOCKER_TAG" .
  - docker tag ghcr.io/nils-witt/s-plan_display:"$DOCKER_TAG" ghcr.io/nils-witt/s-plan_display:"$TRAVIS_COMMIT"
  - echo "$GITHUB_KEY" | docker login ghcr.io -u "$GITHUB_USER" --password-stdin
  - docker push ghcr.io/nils-witt/s-plan_display

script:
  - docker ps